### PR TITLE
Ep jobs add GitHub trigger

### PR DESCRIPTION
**Pull request by karlkranich**
@mikealbert This is a very simple change to add the github trigger to 4 ep jobs.  Want to review, or should I just merge it?

### CODE REVIEW

**Comment by mattdrees** [comment]
Hi Karl, I think maybe you meant to target 'jenkins-2.0' with this PR instead of 'master'?

**Comment by karlkranich** [comment]
Thanks, @mikealbert and @mattdrees.  I just changed it via the github dashboard.  It looks like that worked.  Any further concerns?

**Comment by karlkranich** [comment]
@mikealbert You OK with me merging this after rebasing it via github?

**Comment by mikealbert** [comment]
Yep.

**Pull request merged**
