### PR TITLE
Add more jobs

### PR DESCRIPTION
**Pull request by mattdrees**
generalizes the mpdx job config to all the rails jobs (and one react job)

### CODE REVIEW

**Comment by mattdrees** [comment]
@davidhollenberger can you review this for me?

Let me know if you've got questions.

**Comment by davidhollenberger** [comment]
I don't see any issues.   Layout and formatting look good to me.  It's pretty easy to follow how the individual projects are built from the job templates and job groups.

**Comment by mattdrees** [comment]
Thanks Dave!

**Comment by mattdrees** [comment]
forgot to add a jira link: [CPU-29](https://jira.cru.org/browse/CPU-29)

**Pull request merged**
