### PR TITLE
CPU-62 CPU-63 - Support family life jobs

### PR DESCRIPTION
**Pull request by mattdrees**
This implements both
https://jira.cru.org/browse/CPU-62
and
https://jira.cru.org/browse/CPU-63.

It also makes development easier by adding a pipenv Pipfile.

### CODE REVIEW

**Comment by mattdrees** [comment]
Mike, can you review for me?
Once this is merged, I'll be finished with jenkins-jobs, and you can rebuild jenkins-lab from scratch.

**Comment by mattdrees** [comment]
@vdymna-fl I removed the scm flag, like we discussed. Also, does the familylife-data-api-mbp job definition here look ok to you?

**Comment by vdymna-fl** [comment]
@mattdrees `jobs/pipeline-jobs.yml` looks good to me. One thing is when we finalize everything and actually ready to build the job on `jenkins-prod`, I want to switch the job to a different repo [FamilyLife-FormsAPI](https://github.com/CruGlobal/FamilyLife-FormsAPI). That data-api still needs a lot more work (I was just using it as a guinea pig) and FormsAPI is in production and we are making changes to it. I hope that make sense?

**Comment by mattdrees** [comment]
No, I think the idea of the lock file is that it makes sure anyone who uses this repo gets consistent versions. It's definitely supposed to be tracked by git.

**Comment by mattdrees** [comment]
@vdymna-fl yes, that makes sense; good idea.

**Comment by mattdrees** [comment]
thanks for reviewing, guys!

**Pull request merged**
