### PR TITLE
rename give-ep-docker-images-uat to give-ep-docker-images-develop to …

### PR DESCRIPTION
**Pull request by karlkranich**
Small change to job name and description to match naming convention that has git branch in job name.

### CODE REVIEW

**Comment by mikealbert** [comment]
👍

**Comment by karlkranich** [comment]
@mattdrees , please review this small job name change.

**Comment by karlkranich** [comment]
@mattdrees you can ignore - Mike is going to review this.

**Comment by mattdrees** [comment]
thanks guys

**Pull request merged**
