### PR TITLE
Jenkins 2.0

### PR DESCRIPTION
**Pull request by mikealbert**
@mattdrees @karlkranich I think we are at a point where the jenkins-2.0 branch can be merged into master.  If possible, I'd like to get this done today, so the new Production Jenkins build tomorrow morning can run off the master branch of jenkins-jobs.

I see that automatic merge isn't available for this pr, so not sure how we need to handle that.

### CODE REVIEW

**Comment by mattdrees** [comment]
We need to deal with a conflict. Probably best thing to do is merge master into jenkins-2.0. (I'd normally rebase the branch instead, but for a long, "historied" branch like this I don't think we should rewrite commits.

**Comment by karlkranich** [comment]
I haven't dealt with a git situation quite like this.  I can look into it, unless @mattdrees wants to just do it.

**Comment by mattdrees** [comment]
I'd be happy to let one of you two guys handle it. If you get stuck let me know, but I don't think it will be that hard.

**Comment by karlkranich** [comment]
@mikealbert I'll leave it with you, unless you really want to pass it off.

**Comment by mikealbert** [comment]
@karlkranich I've got it.

**Comment by mikealbert** [comment]
@mattdrees I merged master into this branch.  Can one of you review?

**Comment by mikealbert** [comment]
Seems like there is an issue with this branch (maybe due to the merge).  I'm trying to create jobs on my Jenkins lab instance and it is failing.  Let me try to get that sorted out.

**Comment by mikealbert** [comment]
Duplicate job definitions from the merge caused an issue.  This one should be ready for review now.  @mattdrees

**Comment by karlkranich** [comment]
Everything looks good to me, except that the description of the Pull Request still says "	mikealbert  wants to merge 56 commits into master from jenkins-2.0", so I'm confused what will happen when we click "Merge pull request", since you've commented that you're merging master into jenkins-2.0.

**Comment by mattdrees** [comment]
When we click 'merge pull request', this jenkins-2.0 branch will get merged into master.  The merge that Mike referenced was 81d181b (and 0720305), which merged some recent master changes into jenkins-2.0. Now, there is nothing in master that is not in this jenkins-2.0 branch; there are no conflicts; and the button will do exactly what we want.

**Comment by karlkranich** [comment]
Excellent -- thanks for the explanation @mattdrees

**Pull request merged**
